---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
ggdc:::dc_set_chunk_opts()
library(dplyr)
library(ggplot2)
```

# ggdc

<!-- badges: start -->
<!-- badges: end -->

The goal of ggdc is to provides Datacamp themes for ggplot2.

## Installation

You can install the package from github using `devtools`.

``` r
devtools::install_github("datacamp/ggdc")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example_1}
library(ggdc)
p <- diamonds %>% 
  ggplot(aes(x = carat, y = price, color = cut)) +
  geom_point(alpha = 0.6) +
  labs(
    title = "Price vs. Carat",
    subtitle = 'Weightier diamonds are more expensive'
  ) +
  scale_color_datacamp(palette = 'accents_light')

p +
  theme_datacamp_light()
```

```{r example_2}
p + theme_datacamp_dark()
```

## Example 2

```{r example-3}
diamonds %>% 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_wrap(~ cut, scales = 'free_y') +
  labs(
    title = 'Histogram of Diamonds Prices',
    caption = 'Source: ggplot2'
  ) +
  theme_datacamp_light() +
  scale_fill_datacamp()
```

